# Generated by Django 4.0.1 on 2022-06-01 09:36

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('agency', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=50)),
            ],
            options={
                'unique_together': {('username', 'agency')},
            },
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.CharField(max_length=30)),
                ('type', models.CharField(max_length=200)),
                ('link', models.CharField(max_length=500)),
                ('reference_number', models.CharField(max_length=100)),
                ('pub_update', models.DateTimeField(default=datetime.datetime(2022, 6, 1, 9, 36, 28, 791357, tzinfo=utc))),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listings.user')),
            ],
            options={
                'unique_together': {('username', 'reference_number')},
            },
        ),
    ]
