# Generated by Django 4.0.1 on 2022-06-01 11:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_alter_listing_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='listing',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='listing',
            name='agency',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='listing',
            name='pub_update',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 1, 11, 50, 2, 317550, tzinfo=utc)),
        ),
        migrations.AlterUniqueTogether(
            name='listing',
            unique_together={('agency', 'reference_number')},
        ),
    ]
