# Generated by Django 4.0.1 on 2022-06-01 11:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_alter_listing_unique_together_listing_agency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='link',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='pub_update',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 1, 11, 52, 11, 931324, tzinfo=utc)),
        ),
    ]
